
server:
  port: 3000
spring:
  application:
    name: VET_APIGATEWAY
  cloud:
    gateway:
      routes:
      - id: VET-PERFIL-SERVICE
        uri: lb://VET-PERFIL-SERVICE
        predicates:
          - Path=/perfil/**

      - id: VET-CLINIC-SERVICE
        uri: lb://VET-CLINIC-SERVICE
        predicates:
          - Path=/clinic/**
        filters:
          - StripPrefix=2
      - id: VET-USER-SERVICE
        uri: lb://VET-USER-SERVICE
        predicates:
          - Path=/api/users/**
        filters:
          - StripPrefix=1
      - id: VET-AUTH-SERVICE
        uri: lb://VET-AUTH-SERVICE
        predicates:
          - Path=/api/auth/**
        filters:
          - StripPrefix=1
#eureka client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    hostname: localhost
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: info,health,metrics