eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost
        instance-id: ${spring.application.name}:${random.uuid}
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: info,health,metrics
server:
    port: ${PORT:0}
spring:
    application:
        name: VET-PERFIL-SERVICE
    data:
        mongodb:
            host: localhost
            port: 27017
            authentication-database: admin
            username: nick
            password: "1234"
            database: vet_app
          
